config/routes.rb
Rails.application.routes.draw do
  resources :topics do
    # #34 pass "resources :posts" to the "resources :topics" block. This nests the post routes under the topic routes
    resources :posts, except: [:index]
  end

  # #4 we use only: [] because we don't want to create any /posts/:id routes, just posts/:post_id/comments routes
  resources :posts, only: [] do
  # #5 only add create and destroy routes for comments. We'll display comments on the posts show view, so we won't need index or new routes. We also won't give users the ability to view individual comments or edit comments, removing the need for show, update, and edit routes
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  # These new lines create POST routes at the URL posts/:id/up-vote and  posts/:id/down-vote. The as key-value pairs at the end stipulate the method names which will be associated with these routes: up_vote_path and  down_vote_path
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  # #7
  resources :users, only: [:new, :create, :show]

  post 'users/confirm' => 'users#confirm'

  resources :sessions, only: [:new, :create, :destroy]


  # #2 we remove "get "welcome/index" because we've declared the index view as the root view. We also modify the "about" route to allow users to visit "/about" rather than "/welcome/about"
  get 'about' => 'welcome#about'
  # 'root' declares the default page the app loads when we navigate to the home page URL. "root" is a method that takes a hash as an argument. here we use implied hash syntax instead of: root{{to: 'welcome#index'}}
  root 'welcome#index'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy

  validates :name, length: { minimum: 5 }, presence: true
  validates :description, length: { minimum: 15 }, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # #7 use the before_action filter and the require_sign_in method from  ApplicationController to redirect guest users who attempt to access controller actions other than index or show
  before_action :require_sign_in, except: [:index, :show]
  # #8 use another before_action filter to check the role of signed-in users. If the current_user isn't an admin, we'll redirect them to the topics index view
  before_action :authorize_user, except: [:index, :show, :new, :create]
  before_action :authorize_moderator, only: [:new, :create, :delete]

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      redirect_to @topic, notice: "Topic was saved successfully."
    else
      flash.now[:alert] = "Error creating topic. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])

    @topic.assign_attributes(topic_params)

    if @topic.save
      flash[:notice] = "Topic was updated."
      redirect_to @topic
    else
      flash.now[:alert] = "Error creating topic. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.destroy
      flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the topic."
      render :show
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :description, :public)
  end

  # #9 define authorize_user, which is used in #8 to redirect non-admin users to topics_path (the topics index view)
  def authorize_user
    unless current_user.admin? || current_user.moderator?
      flash[:alert] = "You must be an admin or moderator to do that."
      redirect_to topics_path
    end
  end

  def authorize_moderator
    return unless current_user.moderator?

    flash[:alert] = "You must be an admin to do that."
    redirect_to topics_path
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_for_topics?
    current_user && current_user.admin?
  end

  def moderator_authorized_for_update?
    if current_user
      current_user.moderator?
    else
      false
    end
  end
end

app/views/topics/_topic.html.erb
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
<!-- #8 create a link to the show view for each topic -->
      <%= link_to topic.name, topic %>
    </h4>
    <small>
      <%= topic.description %>
    </small>
  </div>
</div>

app/views/topics/_topicform.html.erb
<%= form_for topic do |f| %>
  <% if topic.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(topic.errors.count, "error") %>.</h4>
      <ul>
        <% topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(topic.errors[:name]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
  <% end %>
  <%= form_group_tag(topic.errors[:description]) do %>
    <%= f.label :description %>
    <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
  <% end %>
  <div class="form-group">
    <!-- #11 pass a block to f.label to generate the HTML for a checkbox -->
    <%= f.label :public, class: 'checkbox' do %>
      <%= f.check_box :public %> Public topic
    <% end %>
  </div>
  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile when you type.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'topicform', locals: { topic: @topic } %>
  </div>
</div>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
  <div class="col-md-8">
    <!-- #7 loop over each topic in @topics -->
    <% @topics.each do |topic| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
    <!-- #8 create a link to the show view for each topic -->
            <%= link_to topic.name, topic %>
          </h4>
          <small>
            <%= topic.description %>
          </small>
        </div>
      </div>
    <% end %>
  </div>
  <!-- #12 check if there is a signed-in current_user, and that current_user is an admin -->
  <% if current_user %>
    <div class="col-md-4">
      <!-- #9 create a link to create a new topic -->
      <%= link_to "Start a New Topic", new_topic_path, class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile when you type.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'topicform', locals: { topic: @topic } %>
  </div>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<% if user_is_authorized_for_topics? %>
  <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
  <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this topic?' } %>
<% end %>

<% if moderator_authorized_for_update? %>
  <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
<% end %>

<div class="row">
  <div class="col-md-8">
    <p class="lead"><%= @topic.description %></p>
    <!-- #10 -->
    <% @topic.posts.each do |post| %>
      <div class="media">
        <%= render partial: 'votes/voter', locals: { post: post} %>
        <div class="media-body">
          <h4 class="media-heading">
<!-- #39 refactor how we link to individual posts using the topic_post_path method. This helper takes a topic and a post and gererates a path to the posts show view -->
            <%= link_to post.title, topic_post_path(@topic, post) %>
          </h4>
<!-- #40 add submission and comment details for each post in the show view -->
          <small>
            submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
            <% post.comments.count %> Comments
          </small>
        </div>
      </div>
    <% end %>
  </div>
  <% if current_user %>
    <div class="col-md-4">
<!-- #41 replace new_post_path with new_topic_post_path to reflect the nested route generated in routes.rb-->
      <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
    </div>
  <% end %>
</div>