config/routes.rb
Rails.application.routes.draw do
  resources :topics do
    # #34 pass "resources :posts" to the "resources :topics" block. This nests the post routes under the topic routes
    resources :posts, except: [:index]
  end

  # #4 we use only: [] because we don't want to create any /posts/:id routes, just posts/:post_id/comments routes
  resources :posts, only: [] do
  # #5 only add create and destroy routes for comments. We'll display comments on the posts show view, so we won't need index or new routes. We also won't give users the ability to view individual comments or edit comments, removing the need for show, update, and edit routes
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  # These new lines create POST routes at the URL posts/:id/up-vote and  posts/:id/down-vote. The as key-value pairs at the end stipulate the method names which will be associated with these routes: up_vote_path and  down_vote_path
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  # #7
  resources :users, only: [:new, :create, :show]

  post 'users/confirm' => 'users#confirm'

  resources :sessions, only: [:new, :create, :destroy]


  # #2 we remove "get "welcome/index" because we've declared the index view as the root view. We also modify the "about" route to allow users to visit "/about" rather than "/welcome/about"
  get 'about' => 'welcome#about'
  # 'root' declares the default page the app loads when we navigate to the home page URL. "root" is a method that takes a hash as an argument. here we use implied hash syntax instead of: root{{to: 'welcome#index'}}
  root 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  # create relation of post class to comment class. The comment class already relates to the post class because of the model generator. The "has_many" method allows the post intance to have many comments related to it and also provides methods that allow us to retrieve comments that belong to a post. Comments are dependent on a post's existence because of the  has_many :comments declaration in Post. When we delete a post, we also need to delete all related comments. We'll perform a "cascade delete", which ensures that when a post is deleted, all of its comments are too
  has_many :comments, dependent: :destroy
  # #4 add the votes association to Post. This relates the models and allows us to call post.votes. We also add dependent: :destroy to ensure that votes are destroyed when their parent post is deleted
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
# default_scope will order all posts by rank by default. Since we want the largest rank numbers displayed first, we'll use descending (DESC) order
  default_scope { order('rank DESC') }
# #15 use a lambda (->) to ensure that a user is present or signed in. If the user is present, we return all posts. If not, we use the  Active Record joins method to retrieve all posts which belong to a public topic. This query uses a SQL 'inner join' to query a collection's relations in one query
  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

# Remember that votes in the below code is an implied self.votes
  def up_votes
    # #9 find the up votes for a post by passing value: 1 to where. This fetches a collection of votes with a value of 1. We then call count on the collection to get a total of all up votes
    votes.where(value: 1).count
  end

  def down_votes
    # #10 find the down votes for a post by passing value: -1 to where.  where(value: -1) fetches only the votes with a value of -1. We then call count on the collection to get a total of all up votes
    votes.where(value: -1).count
  end

  def points
    # #11 use ActiveRecord's sum method to add the value of all the given post's votes. Passing :value to sum tells it what attribute to sum in the collection
    votes.sum(:value)
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # #12 use a before_action filter to call the require_sign_in method before each of our controller actions, except for the show action
  before_action :require_sign_in, except: :show
  # #10 use a second before_action filter to check the role of a signed-in user. If the current_user isn't authorized based on their role, we'll redirect them to the posts show view
  before_action :authorize_user, except: [:show, :new, :create]

  before_action :authorize_moderator, only: [:destroy]

  def show
    # #19 find the post that corresponds to the id in the params that was passed to "show" and assign it to @post. Unlike in the "index' method, in the "show" method, we populate an instance variable with a single post, rather than a collection of posts
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    # #7 create an instance variable, @post, then assign it an empty post returned by Post.new
    @post = Post.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.build(post_params)
    # #14 assign @post.user the same way as @post.topic was assigned above to properly scope the new post
    @post.user = current_user
    # #10 if we successfully save Post to the database, we display a success message using flash[:notice] and redirect the user to the route generated by @post. Redirecting to @post will direct the user to the posts show view
    if @post.save
      # #11 assign a value to flash[:notice]. The "flash" hash provides a way to pass temporary values between actions. Any value placed in "flash" will be available in the next action and then deleted
      flash[:notice] = "Post was saved."
      # #36 change the redirect to use the nested post path
      redirect_to [@topic, @post]
    else
      # #12 if we do not successfully save Post to the database, we display an error message and render the new view again
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)

    if @post.save
      flash[:notice] = "Post was updated."
      # #37 change the redirect to use the nested post path
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "There was an error saving your post. Please try again."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    # #8 call destroy on @post. If that call successful, we set a flash message and redirect the user to the posts index view. If destroy fails then we redirect user to the show view using render :show
    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      # #38 when a post is deleted, we direct users to the topic show view
      redirect_to @post.topic
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end

  def authorize_moderator
    return unless current_user.moderator?

    post = Post.find(params[:id])
      flash[:alert] = "This is not allowed for moderators."
      redirect_to [post.topic, post]
  end

  def authorize_user
    return unless current_user.member?

    post = Post.find(params[:id])
    unless current_user == post.user
      flash[:alert] = "This is not allowed for members."
      redirect_to [post.topic, post]
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_is_authorized_for_post?(post)
    current_user && (current_user == post.user || current_user.admin?) && !current_user.moderator?
  end

  def moderator_authorizations_for_post?(post)
    if current_user
      current_user.moderator?
    else
      false
    end
  end
end

app/views/posts/_form.html.erb
<!-- #3 use the "topic" and "post" local variables we passed into the partial when we rendered it -->
<%= form_for [topic, post] do |f| %>
  <% if post.errors.any? %>
  <!-- # #6 if there are any validation errors, we display an alert with the number of errors and their messages-->
    <div class="alert alert-danger">
  <!-- # #7 use the pluralize method to pluralize "error" if there is more than one error-->
      <h4><%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!-- # #8 use  form_group_tag to display title errors -->
  <%= form_group_tag(post.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
  <% end %>
  <!-- # #9 use form_group_tag to display body errors -->
  <%= form_group_tag(post.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="media">
  <%= render partial: 'votes/voter', locals: { post: post } %>
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to post.title, topic_post_path(post.topic, post) %>
    </h4>
    <small>
      submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
      <%= post.comments.count %> Comments
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
<!-- locals: { topic: @post.topic, post: @post } passes local variables to the partial. @post.topic and @post are assigned to topic and post, respectively. This means we can refer to these local variables, rather than the @post instance variable we used in the edit view. -->
    <%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
   </div>
 </div>

app/views/posts/show.html.erb
<div>
  <%= render partial: 'votes/voter', locals: { post: @post } %>
  <h1>
    <%= @post.title %> <br>
    <small>
      submitted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.name %>
    </small>
  </h1>
</div>
  <div class="row">
    <div class="col-md-8">
      <p><%= @post.body %></p>
      <div>
        <h3>Comments</h3>
        <%= render @post.comments %>
      </div>
  <!-- #19 allow signed in users to see the comment form -->
      <% if current_user %>
  <!-- #20 render the comment form, and use comments/form, because we are rendering the comment form from a post view. If we didn't specify comments, Rails would render the posts form partial by default-->
        <%= render 'comments/form', comment: Comment.new, post: @post %>
      <% end %>
    </div>
    <% if user_is_authorized_for_post?(@post) %>
      <div class="col-md-4">
        <!--#42 replace edit_post_path with edit_topic_post_path which takes two arguments, a topic and a post -->
        <%= link_to "Edit", edit_topic_post_path(@post.topic, @post), class: 'btn btn-success' %>
        <!-- #9 use link_to to create a delete button. The text of the button is "Delete Post". We override the default method (:post) with :delete so that when the button is pressed the route called is the delete route. We style the button by setting class: to 'btn btn-danger'. We pass a Hash with the  confirm: key to the data: argument. This confirms the action with a JavaScript confirmation dialog when a user presses the button. # 43 We updated link_to to take an array consisting of a topic and post which it uses to build the link to delete a nested post -->
        <%= link_to "Delete Post", [@post.topic, @post], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %>
      </div>
    <% end %>

    <% if moderator_authorizations_for_post?(@post) %>
      <div class="col-md-4">
        <%= link_to "Edit", edit_topic_post_path(@post.topic, @post), class: 'btn btn-success' %>
      </div>
    <% end %>
    <div class="col-md-4">
      <h3>
  <!-- #14 use the pluralize helper method to display the correctly pluralized forms of "point", "up vote", and "down vote"-->
        <%= pluralize(@post.points, 'point') %>
        <div>
          <small>
            <%= pluralize(@post.up_votes, 'up vote') %>
            <%= pluralize(@post.down_votes, 'down vote') %>
          </small>
        </div>
      </h3>
      <% if current_user %>
        <%= render partial: 'favorites/favorite', locals: { post: @post } %>
      <% end %>
    </div>
  </div>