config/routes.rb
Rails.application.routes.draw do
  resources :topics do
    # #34 pass "resources :posts" to the "resources :topics" block. This nests the post routes under the topic routes
    resources :posts, except: [:index]
  end

  # #4 we use only: [] because we don't want to create any /posts/:id routes, just posts/:post_id/comments routes
  resources :posts, only: [] do
  # #5 only add create and destroy routes for comments. We'll display comments on the posts show view, so we won't need index or new routes. We also won't give users the ability to view individual comments or edit comments, removing the need for show, update, and edit routes
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  # These new lines create POST routes at the URL posts/:id/up-vote and  posts/:id/down-vote. The as key-value pairs at the end stipulate the method names which will be associated with these routes: up_vote_path and  down_vote_path
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  # #7
  resources :users, only: [:new, :create, :show]

  post 'users/confirm' => 'users#confirm'

  resources :sessions, only: [:new, :create, :destroy]


  # #2 we remove "get "welcome/index" because we've declared the index view as the root view. We also modify the "about" route to allow users to visit "/about" rather than "/welcome/about"
  get 'about' => 'welcome#about'
  # 'root' declares the default page the app loads when we navigate to the home page URL. "root" is a method that takes a hash as an argument. here we use implied hash syntax instead of: root{{to: 'welcome#index'}}
  root 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccit</title>
  <!-- the "viewport meta" tag added inside the <head> instructs browsers on small, high pixel density screens to display our pages at a regular, readable size -->
  <meta name="viewport" content="width=device-width, iniial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Bloccit", root_path %></li>
      <li><%= link_to "Topics", topics_path %></li>
      <li><%= link_to "About", about_path %></li>

      <div class="pull-right user-info">
        <% if current_user %>
  <!-- #9 use image_tag and populate it with the result of avatar_url. We set the class to "gravatar" which we will use to style the avatar -->
          <%= image_tag current_user.avatar_url(48), class: "gravatar" %>
          <div class="pull-right">
  <!-- #10 move our pre-existing code into a new  <div class="pull-right"> so that it floats to the right of the avatar -->
            <%= link_to current_user.name, user_path(current_user) %> <br/> <%= link_to "Sign Out", session_path(current_user), method: :delete %>
          </div>
        <% else %>
          <%= link_to "Sign In", new_session_path %> or
          <%= link_to "Sign Up", new_user_path %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>